trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'


stages:
  - stage: build
    jobs:
    - job: First
      steps:
        - bash: echo "Test"
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: |
              **/*.yaml
              **/*.tf
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'


  - stage: dev
    displayName: Dev Deploy
    jobs:
      - deployment: dev
        environment: dev
        strategy:
          runOnce:
            deploy:
             steps:
               - script: echo "Dev"

  - stage: QA
    displayName: QA Test
    jobs:
      - deployment: QA
        environment: QA
        strategy:
          runOnce:
           deploy:
             steps:
               - script: echo "QA"



  - stage: Dockerbuild
    displayName: Docker Build image
    jobs:  
    - job: DockerBuild
      displayName: DockerBuild
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'DockerReg'
          repository: 'manojlavu/azure-devop'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: '$(tag)'
