trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs:
    - job: First
      steps:
        - bash: echo "Test"
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: |
              **/*.yaml
              **/*.tf
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'


  - stage: dev
    jobs:
      - deployment: dev
        environment: dev
        strategy:
          runOnce:
            deploy:
             steps:
               - script: echo "Dev"



  - stage: QA
    jobs:
      - deployment: QA
        strategy:
          runOnce:
           deploy:
             steps:
               - script: echo "QA"